### ISSUE TITLE
Proposez une musique différente chaque jour 40/40

### ISSUE THREAD

**Issue by alexis92fra** [Filipedel/mu#14]
Chaque jour, le site proposera aux utilisateurs d'écouter une musique tirée au sort parmi une liste de musique préalablement sélectionnée.

**Comment by Jorimou** [comment]
Avant 
![Image](https://user-images.githubusercontent.com/112953170/206062204-75d1c883-6023-43a0-b08f-be587449e08b.png)

Après:
![Image](https://user-images.githubusercontent.com/112953170/206064339-2dd2bdc3-f338-4d9d-9124-9951700301dc.png)

:
