### ISSUE TITLE
Rediriger utilisateur vers son compte pour récupérer son nom utilisateur 10/10

### ISSUE THREAD

**Issue by alexis92fra** [Filipedel/mu#4]
L'utilisateur est redirigé vers son compte via un bouton, afin qu'il récupère son nom d'utilisateur pour le rentrer dans notre site

**Comment by Jorimou** [comment]
![Image](https://user-images.githubusercontent.com/112953170/206068061-f980f3b4-652f-42f9-b14a-03f2dd9f83de.png)



Le bouton nous emmène vers la page Spotify qui nous permet de récuperer notre ID



![Image](https://user-images.githubusercontent.com/112953170/206067601-5ee19845-7de1-493e-8262-f8b3ab4b6db8.png)
